SET LOCK_TIMEOUT 100;

DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS TRANSACTION;
DROP SEQUENCE IF EXISTS TRANSACTION_SEQ;

CREATE TABLE ACCOUNT (
  id        VARCHAR(255) PRIMARY KEY NOT NULL,
  balance   DECIMAL(20, 2) NOT NULL,
  created   TIMESTAMP NOT NULL
);

CREATE SEQUENCE TRANSACTION_SEQ;

CREATE TABLE TRANSACTION (
  id              bigint auto_increment PRIMARY KEY NOT NULL,
  account_to_id   VARCHAR(255) NOT NULL,
  account_from_id VARCHAR(255) NOT NULL,
  amount          DECIMAL(20, 2) NOT NULL,
  created         TIMESTAMP NOT NULL
);
